feat(storybook): add theme support
sideshiftfi/sifi pull request #195
Opened 2023-09-06 13:29 UTC by tommy0x

### Changes Made

- Add Theme Support to Storybook, which now sets the default theme to dark

### Screenshots/videos

<img width="637" alt="Screenshot 2023-09-06 at 15 29 05" src="https://github.com/sideshiftfi/sifi/assets/128688932/f03645eb-aec4-455d-b87f-bd0b2b8934cf">

### Checklist

Please tick the boxes that apply and provide additional details where necessary. Add or edit items as needed.

- [x] Changes are limited to a single goal.
- [x] Responsive design has been tested and looks good on all devices and screen sizes.
- [x] Changes have been tested on all major browsers (Chrome, Firefox, Safari).
- [x] The changes in Chromatic UI Tests all look good.
- [x] No accessibility issues have been introduced in Storybook's Accessibility tab.
- [x] The code has been optimized for performance.

### Related

Closes #185

2023-09-12 09:08 UTC, immutablegoblin requested changes

2023-09-12 09:08 UTC, immutablegoblin commented on packages/frontend/.storybook/main.cjs
> +    '@storybook/addon-styling',
[This is deprecated](https://www.npmjs.com/package/@storybook/addon-styling), we should be using [@storybook/addon-themes](https://github.com/storybookjs/storybook/tree/next/code/addons/themes)

2023-09-13 09:11 UTC, immutablegoblin commented
Should be tested with https://github.com/sideshiftfi/sifi/pull/213

2023-09-19 12:52 UTC, tommy0x commented
> Should be tested with #213

Tested and working on my end after rebasing.

2023-09-19 13:12 UTC, immutablegoblin approved these changes

2023-09-19 14:25 UTC, boriskubrik approved these changes

2023-09-19 14:25 UTC, merged